version: '3'
services:
  python3:
    restart: always
    build: ./docker/
    container_name: 'python3'
    working_dir: '/app'
    tty: true
    volumes:
      - ./src:/app
      - ./gcp.json:/gcp.json
      - ./gcp.env:/.env
      - ./aws.config:/root/.aws/config
      - ./aws.credentials:/root/.aws/credentials
